### ISSUE TITLE
Fails to compile with gcc 4.8

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/libwally-core#176]
I'm surprised it works with any gcc, in fact:

```
  CC                      = gcc-4.8
  CFLAGS                  = -g -W -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wno-unused-function -Wno-long-long -Wno-overlength-strings -fvisibility=hidden -O3
```

Note the `-std=c89` (which AFAICT comes from libsecp):

Sure enough, libwally is not C89.  For example:

```
../../libwally-core/src/address.c: In function ‘wally_bip32_key_to_address’:
../../libwally-core/src/address.c:25:5: warning: C++ style comments are not allowed in ISO C90 [enabled by default]
     // Catch known incorrect combinations of address type and version:
     ^
../../libwally-core/src/address.c:25:5: warning: (this will be reported only once per input file) [enabled by default]
../../libwally-core/src/elements.c: In function ‘wally_asset_pak_whitelistproof’:
../../libwally-core/src/elements.c:629:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < num_keys; ++i) {
     ^
../../libwally-core/src/elements.c:629:5: note: use option -std=c99 or -std=gnu99 to compile your code
../../libwally-core/src/sign.c: In function ‘wally_ec_sig_to_public_key’:
../../libwally-core/src/sign.c:324:5: warning: ISO C90 forbids mixed declarations and code [-Wpedantic]
     int recid = (sig[0] - 27) & 3;
     ^
```

**Comment by glslang** [comment]
Should compile now with -std=c89. Please do let us know if you're still seeing errors.

**Comment by vasild** [comment]
FWIW the above mentioned CFLAGS that include an explicit `-std=c89` are only used to compile `src/secp256k1` which is C89 compliant and this is fine.

libwally's own source files are compiled without an explicit `-std=`. For an exact compilation command see the commit message of https://github.com/ElementsProject/lightning/pull/3561/commits/6395c4340b6efe5a463fbf2d47b76726e62a7041.

Recent compilers default to C99 or newer, but gcc 4.8 [defaults to gnu89](https://gcc.gnu.org/onlinedocs/gcc-4.8.5/gcc/C-Dialect-Options.html#C-Dialect-Options).

This also fixes the issue:
```diff
--- i/configure.ac
+++ w/configure.ac
@@ -11,12 +11,14 @@ AH_BOTTOM([#include "ccan_config.h"
 #endif /*LIBWALLYCORE_CONFIG_H*/])

 # Remove any optimisation/debug flags from CFLAGS, these are controlled
 # only by --enable-debug, in order to only use tested configurations
 CFLAGS=`echo $CFLAGS | sed 's/-[Og][0-9]*[ $$]*//'`

+CFLAGS="$CFLAGS -std=c99"
+
 LDPATH_VAR=LD_LIBRARY_PATH
 case $host_os in
 *darwin*)
     is_osx="yes"
     LDPATH_VAR=DYLD_LIBRARY_PATH
     ;;
```

**Comment by vasild** [comment]
That was the easier way to get it to compile from within c-lightning. Once the fix for this gets tagged (I guess `release_0.7.8`) it would be possible to remove [the workaround](https://github.com/ElementsProject/lightning/commit/6e86022909f167a0488033ec155f19436e694852).

**Comment by NickeZ** [comment]
It seems like the maintainers of c-lightning choose to bump to a commit hash instead of a version for now. I agree with you that maybe a workaround would have been less risky until there is a new libwally release.
